# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed867bff1553c7f7277ff135c4e66f026e0d057b97babd83c586d03ee0f6aa200f2995caa412401c018eedc6584f61ab897907fe93ddc594c36ec5a499933916

test:
  secret_key_base: 3ed9234ba554232729833a1efa8ac737d7723cd7050dde0ce95cb1a9857239f4801e7b7249bf61000555c850c868a06ee84ddfcb38879e9dd248437ea807dc70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
